### PR TITLE
+ add taskKillGracePeriodSeconds

### PR DESCRIPTION
**Pull request by kulikov**
Available since marathon 1.3.0

Docs https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/public/api/v2/types/app.raml#L237

ref to #171

### CODE REVIEW

**Comment by gambol99** [comment]
Cheers for the PR @kulikov  ... If this is a configurable option, perhaps we can add getters and setters? ... similar to https://github.com/gambol99/go-marathon/blob/master/application.go#L164-L259 ...

**Comment by kulikov** [comment]
done

**Comment by kulikov** [comment]
Only 3 methods has `Set` prefix: SetApplicationVersion, SetDiscovery and SetIPAddressPerTask.

But yes, we can ^)

**Comment by timoreimann** [comment]
I should have said `Set` or `Add`. The newer methods normally have it.

**Comment by kulikov** [comment]
ok, thanks

**Comment by timoreimann** [comment]
Sorry, I only realize now that we have extended the JSON methods by the new field but don't use it anywhere for testing. IMHO, we should either remove them from the yaml file or add a deserialization test assertion.

**Comment by kulikov** [comment]
done. at first i just add field everywhere, like maxLaunchDelaySeconds

**Comment by timoreimann** [comment]
LGTM -- thanks a lot!

**Pull request merged**
