### PR TITLE
Fix golint errors in events.go and its consumers.

### LINKED ISSUE #80: Golint conformance
I'm opening this issue here for discussion on the subject. @eicca suggested (https://github.com/gambol99/go-marathon/pull/79#issuecomment-152015182) that we might consider making project code meet golint rules. However, there are many places which are not just simply missing doc comments but require renaming of exported names. This will definitely be a breaking change. So, two questions here:
* Do we introduce a versioning strategy? (Also to track Marathon API changes)
* Do we try to make code meet golint rules?

### PR DESCRIPTION
**Pull request by timoreimann**
**BREAKING CHANGE PSA:** This commit changes all public event ID names and a few struct field names. Consumers will need to adjust, unfortunately.

Closes #80.

### CODE REVIEW

**Comment by timoreimann** [comment]
@eicca would you like to review?

**Comment by timoreimann** [comment]
Pinging @gambol99 as potential reviewer too just in case :-)

**Comment by gambol99** [comment]
absolutely! ... always hated those .. and i was the one who did it :-) ... LGTM

**Comment by timoreimann** [comment]
Thanks ☺️

**Pull request merged**
