### PR TITLE
Expose task state.

### PR DESCRIPTION
**Pull request by timoreimann**
Knowing the task state can be useful for a variety of reasons. The one I specifically have in mind is to exclude tasks from load balancing rotation that have transitioned into the `TASK_KILLING` state in order to implement [graceful termination](https://mesosphere.github.io/marathon/docs/health-checks.html).

### CODE REVIEW

**Comment by timoreimann** [comment]
Tested the unmarshaling and found to be working.

**Comment by timoreimann** [comment]
@gambol99 a quick look? :-)

**Comment by gambol99** [comment]
hi @timoreimann  ... LGTM

**Comment by timoreimann** [comment]
@gambol99 thanks! :tada:

**Pull request merged**
