### PR TITLE
Check a single application for status instead of all

### LINKED ISSUE #95: HasApplication uses ListApplications and retrieves entire state of marathon
When using the HasApplication function go-marathon queries through to marathon with the `apps` endpoint. In deployments with large numbers of applications this causes marathon to return a significant amount of data. Functionally, HasApplication seems nearly equivalent to Application (it just handles the ErrDoesNotExist error by returning a falsey value). 

Is there any difference between the approach I describe and the current implementation with ListApplications?

If not, I'm happy to submit a PR to improve this. Thanks!

### PR DESCRIPTION
**Pull request by tracycodes**
Fixes #95

### CODE REVIEW

**Comment by gambol99** [comment]
:+1: LGTM

**Comment by timoreimann** [comment]
@gambol99 did you forget to merge after your LGTM? Or is anything still holding us back?

**Comment by gambol99** [comment]
@timoreimann .. just my forgetful self :-) ... merging now ..

**Comment by timoreimann** [comment]
awesomely quick response. appreciated! 👌

**Pull request merged**
