### PR TITLE
Fix: cluster members may have url prefix

### PR DESCRIPTION
**Pull request by fsamin**
see #179

### CODE REVIEW

**Comment by gambol99** [comment]
cheers for this @fsamin ... could be we have a quick test for with and without paths ... perhaps based off to https://github.com/gambol99/go-marathon/blob/master/cluster_test.go#L47

**Comment by fsamin** [comment]
No problem @gambol99, I'll write this test.

**Comment by fsamin** [comment]
Hi @gambol99, I add a test with a path. URL without Path were already tested.
Regards

**Comment by gambol99** [comment]
lgtm

**Pull request merged**
