### PR TITLE
marathon task.Ipaddresses field added

### PR DESCRIPTION
**Pull request by dmajere**
Good day,
since marathon version 1.1.1 additional field in Task structure has been introduced.
It look like this.
`            
"ipAddresses": [
                {
                    "ipAddress": "0.0.0.0",
                    "protocol": "IPv4"
                }
            ]
`

### CODE REVIEW

**Comment by dmajere** [comment]
I found out that ipAddresses field is also appeared in Event structure, but I don't know where is a better place for IpAddress struct, should I create ipam.go file for it? Any suggestions?

**Comment by timoreimann** [comment]
@dmajere I assume that tasks can be considered the real owner of this new struct, whereas events simply "consume" it. In that sense, I'd keep it in `task.go` and just reference from whereever needed. In fact, already do this in `event.go` for other structs.

Could you please point me to the Marathon documentation of this new struct? Thanks!

**Comment by dmajere** [comment]
It seems that there is no information about it in documentation yet.
I found this field first in marathon dashboard.
Here are code snippets from marathon with classes for status update event and launched task.
 
src/main/scala/mesosphere/marathon/event/Events.scala
`
221 case class MesosStatusUpdateEvent(
222   slaveId: String,
223   taskId: Task.Id,
224   taskStatus: String,
225   message: String,
226   appId: PathId,
227   host: String,
228   ipAddresses: Option[Seq[org.apache.mesos.Protos.NetworkInfo.IPAddress]],
229   ports: Seq[Int],
230   version: String,
231   eventType: String = "status_update_event",
232   timestamp: String = Timestamp.now().toString) extends MarathonEvent`

src/main/scala/mesosphere/marathon/core/task/Task.scala
`
408   case class Launched(
409       appVersion: Timestamp,
410       status: Status,
411       hostPorts: Seq[Int]) {
412
413     def hasStartedRunning: Boolean = status.startedAt.isDefined
414
415     def ipAddresses: Option[Seq[MesosProtos.NetworkInfo.IPAddress]] =
416       status.mesosStatus.flatMap(MesosStatus.ipAddresses)
417   }
`

**Comment by timoreimann** [comment]
@dmajere Thanks for the pointers.

I overlooked a tiny thing when I reviewed your PR: Could you please upper-case the initialisms in `IpAddress[es]` to `IPAddress[es]` in order to satisfy the [Go Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#initialisms)?

Unfortunately, I don't have a Marathon 1.1.1 copy around right now. Did you possibly test and verify that the struct is populated properly?

**Comment by dmajere** [comment]
>  Could you please upper-case the initialisms in IpAddress[es] to IPAddress[es] in order to satisfy the Go Code Review Comments?

Done.

We've been using go-marathon with this patch for almost a week now and got no problems so far.

**Comment by timoreimann** [comment]
Great to hear. Sounds like it shouldn't cause any problems then.

LGTM. Thanks for contributing!

**Pull request merged**
