### PR TITLE
Add network name to IP-per-task struct.

### LINKED ISSUE #224: ipAddress field not found
To deploy docker containers onto the overlay network, we have to specify `{"ipAddress": {"network": "$MYNETWORK"}}` in the marathon application definition. But I don't see that in the Application struct. 

https://docs.mesosphere.com/1.8/usage/service-discovery/load-balancing-vips/overlay-networks/

### PR DESCRIPTION
**Pull request by timoreimann**
Fixes #224.

### CODE REVIEW

**Comment by timoreimann** [comment]
@yathi-naik do you have an opportunity to try out this branch?

The documentation seems a bit inconsistent: The [page you linked to](https://docs.mesosphere.com/1.8/usage/service-discovery/load-balancing-vips/overlay-networks/) calls the field `network` in the description, while the JSON example there and [here](https://mesosphere.github.io/marathon/docs/ip-per-task.html) goes with `networkName`. The PR uses the latter for now.

Happy to flip that if `network` turns out to be correct.

**Comment by yathi-naik** [comment]
Roger that @timoreimann. I will try out your branch.

**Comment by yathi-naik** [comment]
I guess I need to specify the network parameter in the docker section too. ```To use an overlay network in a Marathon app definition, specify the "network": "USER" property along with an ipAddress field in the form: {"ipAddress": {"network": "$MYNETWORK"}}. The value of $MYNETWORK is the canonical name of the network.``` as mentioned in https://docs.mesosphere.com/1.8/usage/service-discovery/load-balancing-vips/overlay-networks/.

**Comment by timoreimann** [comment]
Sorry to hear it's not working with containers. At least we know now that the PR is working in general.

Okay with you if we merge this one?

**Comment by yathi-naik** [comment]
Please go ahead and merge this one. 👍

**Comment by timoreimann** [comment]
Thanks for the feedback!

**Comment by yathi-naik** [comment]
@timoreimann I'm hitting this error when I call `CreateApplication(application *Application) (*Application, error)` from your branch. Have the API's changed? ``` Error: Marathon API error: URI not found: /apps```

**Comment by timoreimann** [comment]
Looks like the Marathon URL isn't constructed properly. It's certainly not related to the PR. Maybe due to a previous change.

Could you please file a new issue with a small reproducible case? Thanks!

**Comment by yathi-naik** [comment]
Ah yes, my bad. The URL I gave had a trailing `/`. Now I got past that error. And now I hit a new one. ```Error: Marathon API error: Invalid JSON (path: '/ipAddress/discovery/ports' errors: error.path.missing``` :) I'll specify the discovery ports and try again. :)

**Pull request merged**
