### PR TITLE
Remove TimeWaitPolling from marathonClient.

### LINKED ISSUE #217: If using default config, WaitOnDeployment will wait 138 hours in for loop
If I using default config, like [example/application.go](https://github.com/gambol99/go-marathon/blob/master/examples/applications/main.go#L45), it will wait for too long in [waitOnDeployment](https://github.com/gambol99/go-marathon/blob/master/examples/applications/main.go#L106) and got stuck. In fact, it will wait 138h53m20s.

After debugging, we found this issue is caused by [a mistake here](https://github.com/gambol99/go-marathon/blob/master/deployment.go#L154), I think the highlighted line should be

```go
time.Sleep(r.config.PollingWaitTime)
```

In this way, If I set timeout to 800ms like, 

```go
config := marathon.NewDefaultConfig()
config.PollingWaitTime = 800 * time.Millisecond
```

it won't be multiply by 1000000000 [here](https://github.com/gambol99/go-marathon/blob/master/client.go#L215).

WDYT? Please check and confirm this issue. I will push a commit if needed.

### PR DESCRIPTION
**Pull request by timoreimann**
Fixes #217.
Closes #216.

### CODE REVIEW

**Comment by kesselborn** [comment]
haha ... yeah: even better

**Comment by timoreimann** [comment]
@kesselborn @zyfdegh I pushed one last commit (3f77d47). Would you mind taking a look? See also the commit message for a rationale.

**Comment by zyfdegh** [comment]
Good job. It looks better now. But why not use

```go
conf := cl.config
```

directly instead of

```sh
conf := cl.(*marathonClient).conf()
```

inside `func TestNewClient(t *testing.T)`.

I'm a bit confused. What will happen if call directly?

**Comment by timoreimann** [comment]
@zyfdegh The configuration instance is not exported by `marathonClient`, so we can only access it local to the client. I thought about changing its accessibility but decided against it as I don't want to give the impression that the config is something that can (or should) be changed after the client has been created. For similar reasons, I wouldn't want to turn `config` into a pointer (plus, it'd be breaking change).

The type assertion is a bit ugly and will panic if we, for some reason, cast the wrong instance. However, given  that we should be calling this method from a test context only, it's acceptable to me.

Does that sound reasonable?

**Comment by timoreimann** [comment]
Geez, I think what I just wrote actually doesn't make sense as the function I created and the conf struct live on the same accessibility space. Let me double check and simplify if I can. :-)

**Comment by timoreimann** [comment]
@zyfdegh I was right and wrong :-)

Even though the export status isn't a problem, `NewClient` returns an interface which obviously cannot hold data. Thus, we can get rid of the test helper function but not the type assertion.

I pushed 811fb08.

**Comment by timoreimann** [comment]
Time to merge.

**Comment by zyfdegh** [comment]
OK, got it. Anyway, it works good for me.

**Pull request merged**
